parentAccount = ["ALLIANCE TIRE_M",
"APOLLO_M",
"AVAYA_M",
"BAKERLY_M",
"BLUE MOOSE CLOTHING_M",
"CALIFORNIA INNOVATIONS_M",
"WALMART_M",
"CROCS_M",
"DAMCO_M",
"DANBY PRODUCT_M",
"EXPEDITORS _M",
"FERGUSON_M",
"FUJITSU_M",
"INFINERA CORP_M",
"INNOVAIRRE GLOBAL_M",
"INTERPARFUMS_M",
"INTIRION CORPORATION_M",
"JABIL_M",
"KLA_M",
"LL FLOORING_M",
"MORPHE_M",
"MOTOROLA_M",
"MUNCHKIN_M",
"OLD TIME POTTERY_M",
"SANDVIK_M",
"SCHNEIDER_M",
"URBAN OUTFITTERS_M",
"VALARIS_M",
"WILLIAMS SONOMA_M",
"YOKOHAMA_M"]


643fbb458044d21b030c1a89




"profileBase" : [
        {
            "profileBased" : true,
            "isUniqueField" : false,
            "isReadonly" : false,
            "isMandatory" : false,
            "useForCustomReport" : true,
            "label" : "Shipment Type",
            "displayOrder" : NumberInt(5),
            "regex" : null,
            "groupKey" : "shipmentInformation",
            "tariffIdentifier" : false,
            "isMasterField" : false,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "shipmentType",
            "suggestionsSource" : "metadata_shipmentTypes",
            "errorMessage" : "",
            "groupCaption" : "Shipment Information",
            "toolTip" : "Shipment Type",
            "isDependent" : false,
            "key" : "shipmentType",
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(20),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "isDocUPload" : true,
            "isUniqueField" : false,
            "isReadonly" : false,
            "isMandatory" : false,
            "useForCustomReport" : true,
            "label" : "Transport Mode",
            "displayOrder" : NumberInt(6),
            "regex" : null,
            "groupKey" : "shipmentInformation",
            "tariffIdentifier" : true,
            "isMasterField" : false,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "transportMode",
            "suggestionsSource" : "metadata_transportModes",
            "errorMessage" : "",
            "groupCaption" : "Shipment Information",
            "toolTip" : "Transport Mode",
            "isDependent" : false,
            "key" : "transportMode",
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : [

            ],
            "length" : NumberInt(20),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "key" : "billToPartyPartyAccountNumber",
            "isReadonly" : false,
            "isMandatory" : false,
            "useForCustomReport" : true,
            "label" : "Bill To Account Number",
            "displayOrder" : NumberInt(51),
            "regex" : null,
            "groupKey" : "invoice",
            "tariffIdentifier" : false,
            "isMasterField" : false,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionsSource" : "account",
            "errorMessage" : "",
            "groupCaption" : null,
            "toolTip" : "Bill To Account Number",
            "isDependent" : false,
            "isUniqueField" : false,
            "addInAccessSet" : false,
            "isActive" : false,
            "value" : "",
            "length" : NumberInt(25),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "isUniqueField" : false,
            "isReadonly" : false,
            "isMandatory" : false,
            "useForCustomReport" : true,
            "label" : "Origin Station Code",
            "displayOrder" : NumberInt(79),
            "regex" : null,
            "groupKey" : "stationType",
            "tariffIdentifier" : false,
            "isMasterField" : true,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "iataCode",
            "suggestionsSource" : "metadata_airportCode",
            "errorMessage" : "",
            "groupCaption" : "Station Type",
            "toolTip" : "Origin Station Code",
            "isDependent" : false,
            "key" : "originStationCode",
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(35),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "key" : "originAirportCode",
            "isReadonly" : false,
            "isMandatory" : false,
            "useForCustomReport" : true,
            "label" : "Origin Airport Code",
            "displayOrder" : NumberInt(86),
            "regex" : null,
            "groupKey" : "stationType",
            "fieldValidation" : "",
            "tariffIdentifier" : false,
            "isMasterField" : false,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "iataCode",
            "suggestionsSource" : "metadata_airportCode",
            "errorMessage" : "",
            "groupCaption" : "Station Type",
            "toolTip" : "Origin Airport Code",
            "isDependent" : false,
            "isUniqueField" : false,
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(3),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "isUniqueField" : false,
            "isReadonly" : false,
            "isMandatory" : true,
            "useForCustomReport" : true,
            "label" : "Destination Station Code",
            "displayOrder" : NumberInt(102),
            "regex" : null,
            "groupKey" : "stationType",
            "tariffIdentifier" : false,
            "isMasterField" : true,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "iataCode",
            "suggestionsSource" : "metadata_airportCode",
            "errorMessage" : "",
            "groupCaption" : "Station Type",
            "toolTip" : "Destination Station Code",
            "isDependent" : false,
            "key" : "destinationStationCode",
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(35),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "isUniqueField" : false,
            "isReadonly" : false,
            "isMandatory" : true,
            "useForCustomReport" : true,
            "label" : "Service Type",
            "displayOrder" : NumberInt(126),
            "regex" : null,
            "groupKey" : "shipmentInformation",
            "tariffIdentifier" : false,
            "isMasterField" : false,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "serviceType",
            "suggestionsSource" : "metadata_serviceTypes",
            "errorMessage" : "",
            "groupCaption" : "Shipment Information",
            "toolTip" : "Service Type",
            "isDependent" : false,
            "key" : "serviceType",
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(20),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "isUniqueField" : false,
            "isReadonly" : false,
            "isMandatory" : true,
            "useForCustomReport" : true,
            "label" : "Service Level",
            "displayOrder" : NumberInt(127),
            "regex" : null,
            "groupKey" : "shipmentInformation",
            "tariffIdentifier" : false,
            "isMasterField" : false,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "servicelevelcode",
            "suggestionsSource" : "metadata_serviceLevels",
            "errorMessage" : "",
            "groupCaption" : "Shipment Information",
            "toolTip" : "Service Level",
            "isDependent" : false,
            "key" : "serviceLevel",
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(20),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "isUniqueField" : null,
            "isReadonly" : null,
            "isMandatory" : null,
            "useForCustomReport" : true,
            "label" : "Business Unit",
            "displayOrder" : NumberInt(175),
            "regex" : null,
            "groupKey" : "references",
            "tariffIdentifier" : false,
            "isMasterField" : null,
            "isMultiple" : null,
            "type" : "dropdown",
            "isDefault" : null,
            "validationActive" : null,
            "description" : null,
            "suggestionField" : "businessUnit",
            "suggestionsSource" : "metadata_TYCOBusinessUnits",
            "errorMessage" : null,
            "groupCaption" : "References",
            "toolTip" : "Business Unit",
            "isDependent" : null,
            "key" : "businessUnit",
            "addInAccessSet" : null,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(200),
            "customFlag" : null
        },
        {
            "profileBased" : true,
            "key" : "filingStationCountry",
            "isReadonly" : false,
            "isMandatory" : false,
            "useForCustomReport" : true,
            "label" : "Filling Station Country",
            "displayOrder" : NumberInt(219),
            "regex" : null,
            "groupKey" : "stationType",
            "tariffIdentifier" : false,
            "isMasterField" : false,
            "isMultiple" : false,
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionsSource" : "metadata_country",
            "errorMessage" : "",
            "groupCaption" : "Station Type",
            "toolTip" : "Filling Station Country",
            "isDependent" : false,
            "isUniqueField" : false,
            "addInAccessSet" : false,
            "isActive" : false,
            "value" : "",
            "length" : NumberInt(35),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "isUniqueField" : null,
            "isReadonly" : null,
            "isMandatory" : null,
            "useForCustomReport" : true,
            "label" : "Invoice Type",
            "displayOrder" : NumberInt(328),
            "regex" : null,
            "groupKey" : "invoice",
            "tariffIdentifier" : null,
            "isMasterField" : null,
            "isMultiple" : null,
            "type" : "dropdown",
            "isDefault" : null,
            "validationActive" : null,
            "description" : null,
            "suggestionField" : "chargeType",
            "suggestionsSource" : "metadata_chargeType",
            "errorMessage" : null,
            "groupCaption" : null,
            "toolTip" : null,
            "isDependent" : null,
            "key" : "invoiceType",
            "addInAccessSet" : null,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(100),
            "customFlag" : null
        },
        {
            "profileBased" : true,
            "key" : "ServiceType",
            "isReadonly" : false,
            "isMandatory" : true,
            "tariffIdentifier" : false,
            "isMultiple" : false,
            "regex" : null,
            "groupKey" : "shipmentInformation",
            "label" : "Service TypeAMAT",
            "isMasterField" : false,
            "displayOrder" : NumberInt(480),
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "serviceType",
            "suggestionsSource" : "metadata_AMATServiceType",
            "errorMessage" : "",
            "groupCaption" : "SHIPMENT INFORMATION",
            "toolTip" : "Service Type",
            "isDependent" : false,
            "isUniqueField" : false,
            "addInAccessSet" : false,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(20),
            "customFlag" : false
        },
        {
            "profileBased" : true,
            "key" : "fpcName",
            "isReadonly" : null,
            "isMandatory" : null,
            "label" : "FPC name",
            "displayOrder" : NumberInt(576),
            "regex" : null,
            "groupKey" : "shipmentInformation",
            "tariffIdentifier" : null,
            "isMasterField" : null,
            "isMultiple" : null,
            "type" : "dropdown",
            "isDefault" : null,
            "validationActive" : null,
            "description" : null,
            "suggestionsSource" : "metadata_businessUnit",
            "errorMessage" : null,
            "groupCaption" : null,
            "toolTip" : null,
            "isDependent" : null,
            "isUniqueField" : null,
            "addInAccessSet" : null,
            "isActive" : true,
            "value" : [
                {
                    "v" : "Syncada",
                    "id" : "5e78ff473f26c141324a7ea9",
                    "n" : "Syncada"
                }
            ],
            "length" : NumberInt(30),
            "customFlag" : null
        },
        {
            "profileBased" : true,
            "isDocUPload" : null,
            "key" : "creditNoteAllowed",
            "isReadonly" : null,
            "isMandatory" : null,
            "useForCustomReport" : null,
            "label" : "Credit Note Identifier",
            "displayOrder" : NumberInt(738),
            "regex" : null,
            "groupKey" : "invoice",
            "tariffIdentifier" : null,
            "isMasterField" : null,
            "isMultiple" : null,
            "isSystemUniqueField" : null,
            "type" : "dropdown",
            "isDefault" : null,
            "validationActive" : null,
            "description" : null,
            "suggestionField" : null,
            "suggestionsSource" : "metadata_trueFalse",
            "errorMessage" : null,
            "groupCaption" : "Invoice",
            "toolTip" : null,
            "isDependent" : null,
            "isUniqueField" : null,
            "addInAccessSet" : null,
            "isActive" : true,
            "value" : "",
            "length" : NumberInt(20),
            "customFlag" : null
        },
        {
            "profileBased" : true,
            "isUniqueField" : false,
            "isReadonly" : false,
            "isMandatory" : false,
            "useForCustomReport" : true,
            "tariffIdentifier" : false,
            "isMultiple" : false,
            "regex" : null,
            "groupKey" : "stationType",
            "fieldValidation" : "",
            "label" : "Origin Airport Code",
            "isMasterField" : false,
            "displayOrder" : NumberInt(764),
            "type" : "dropdown",
            "isDefault" : false,
            "validationActive" : true,
            "description" : "",
            "suggestionField" : "iataCode",
            "suggestionsSource" : "metadata_airportCode",
            "errorMessage" : "",
            "groupCaption" : "Station Type",
            "toolTip" : "Origin Airport Code",
            "isDependent" : false,
            "key" : "OriginAirportCode",
            "addInAccessSet" : false,
            "isActive" : false,
            "value" : "",
            "length" : NumberInt(3),
            "customFlag" : false
        }
    ],