import pandas as pd
import json
import bson
from bson import json_util
def json_manipulation():
    df = pd.read_csv("account_data.csv")
    df.to_json("_result.json", indent =1, orient="records")
   #keylist = [,"","State","Country Code","Parent Account"]
    with open("_result.json", 'r') as jsonfile:
        data = json.loads(jsonfile.read())
    for records in data:
        if (not records.get("Account Number") or not records.get("Account Name") or not records.get("Address1")
            or not records.get("City") or not records.get("Country name") or not records.get("Zip Code") or not records.get("State") 
            or not records.get("Country Code") ):
            data.pop()
            continue
        # if( not records.get("Account Number") or )
        #     # raise Exception("Some Data is missing")
        #     continue
        else:
            #
            #if records.get("address2"):

            records["address2"] = ""
            records["address3"] = ""
            records["address4"] = ""
            records["shipmentProfile"] = ""
            records["paymentTerm"] = ""
            #are these id autogenerated or we have to extract it
            
            records["system"] = bson.ObjectId("5649d0ce087df204a8a71638")
            records["templateId"] = bson.ObjectId("5649d0c9087df204a8a71636")
            records["organization"] = bson.ObjectId("555af07389025b2b58759bca")
            records["isActive"] = True

    #to overcome below error we used json_util    
    #TypeError: Object of type type is not JSON serializable
    data_obj = json_util.dumps(data, indent=4)
    #data.to_json("result_.json", indent=4)
    #print(data)
    with open("_result.json", 'w') as outputfile:
        outputfile.write(data_obj)
    
    
json_manipulation()

#client = pymongo.MongoClient('mongodb://localhost:27017')
#database = client['invoize-uat']